## Build

FROM    golang:1.17-buster AS build

WORKDIR /app

COPY    go.mod .
COPY    go.sum .
RUN     go mod download

COPY    *.go ./

RUN     go build -o /docker-gs-ping

## Deploy

FROM uffizzi/ttyd:alpine
RUN apk update --quiet \
    && apk add -q --no-cache libgcc tini curl

WORKDIR /

COPY --from=build /docker-gs-ping /bin/docker-gs-ping
RUN chmod +x /bin/docker-gs-ping && ln -s /bin/docker-gs-ping /docker-gs-ping

ENTRYPOINT ["tini", "--"]
CMD     ["ttyd", "/bin/zsh"]
