version: "3"

x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:
  cli-previews:
    image: ${CLI_PREVIEW_IMAGE}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
    - ./uffizzi/nginx:/etc/nginx