version: "3"

x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:
  cli-previews:
    image: "${CLI_PREVIEW_IMAGE}"
    restart: unless-stopped
    ports:
    - "7681:7681"
    - "7700:7700"
    deploy:
      resources:
        limits:
          memory: 500M
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
    - "8081:8081"
    volumes:
    - ./uffizzi/nginx:/etc/nginx