## Build

FROM    golang:1.17-buster AS build

WORKDIR /app

COPY    go.mod .
COPY    go.sum .
RUN     go mod download

COPY    *.go ./

RUN     go build -o /docker-gs-ping

## Deploy

FROM    uffizzi/ttyd:alpine

WORKDIR /

RUN     apk update --quiet \
        && apk add -q --no-cache libgcc tini curl

COPY --from=build /docker-gs-ping /bin/docker-gs-ping
RUN     ln -s /bin/docker-gs-ping /docker-gs-ping

ENTRYPOINT ["tini", "--"]
CMD     ["ttyd", "/bin/zsh"]
